// Moved to @cesium/client (packages/client/src/agent-rail.ts). Re-export shim keeps existing imports stable.
export {
  AGENT_RAIL_ENVIRONMENT_FILTER_KEYS,
  AGENT_RAIL_ENVIRONMENT_FILTER_LABELS,
  AGENT_RAIL_FILTER_PRESETS,
  AGENT_RAIL_FILTER_TOGGLE_KEYS,
  AGENT_RAIL_SOURCE_FILTER_KEYS,
  AGENT_RAIL_SOURCE_FILTER_LABELS,
  AGENT_RAIL_STATUS_FILTER_KEYS,
  AGENT_RAIL_STATUS_FILTER_LABELS,
  createDefaultAgentRailFilterState,
  defaultAgentRailFilterToggles,
  getAgentRailEnvironmentFilterKey,
  getAgentRailSourceFilterKey,
  getAgentRailStatusFilterClass,
  isAgentRailFilterPreset,
  isAgentRailFilterStateActive,
  isPlaceholderAgentRailConversation,
  isRenderableAgentRailConversation,
  matchesAgentRailFilters,
  migrateAgentRailFilterToggles,
  normalizeAgentRailFilterState,
  normalizeAgentRailFilterToggles,
} from "@cesium/client";
export type {
  AgentRailEnvironmentFilterKey,
  AgentRailFilterMatchContext,
  AgentRailFilterPreset,
  AgentRailFilterState,
  AgentRailFilterToggleKey,
  AgentRailFilterToggleState,
  AgentRailSourceFilterKey,
  AgentRailStatusFilterKey,
} from "@cesium/client";
