// Moved to @cesium/core (packages/core/src/protocol.ts). Re-export shim keeps @/lib/agent-types imports stable.
export {
  AGENT_CAPABILITY_KEYS,
  AGENT_STORED_EVENT_KINDS,
} from "@cesium/core";
export type {
  AgentBackendId,
  AgentBackendInfo,
  AgentConfigOption,
  AgentConfigOptionCategory,
  AgentConfigOptionValue,
  AgentContextUsageCategory,
  AgentContextUsageCategoryId,
  AgentContextUsageSnapshot,
  AgentImportResult,
  AgentImportSessionSummary,
  AgentImportSourceInfo,
  AgentConversationConfig,
  AgentConversationConfigPatch,
  AgentConversationCreateInput,
  AgentConversationEventWindow,
  AgentConversationGroup,
  AgentConversationGroupsResult,
  AgentConversationListResult,
  AgentConversationMetadataPatch,
  AgentConversationMode,
  AgentConversationRecord,
  AgentConversationSnapshot,
  AgentConversationSnapshotHead,
  AgentConversationStatus,
  AgentExecutionTarget,
  AgentPendingPermission,
  AgentPendingQuestion,
  AgentPermissionOption,
  AgentPermissionOptionKind,
  AgentPlanEntry,
  AgentProviderCapabilities,
  AgentRailConversationSummary,
  AgentRailRepositoryInfo,
  AgentSocketClientMessage,
  AgentSocketServerMessage,
  AgentStoredEvent,
  AgentStoredEventBase,
  AgentStoredEventKind,
  AgentToolCallStatus,
  AgentToolEditPreview,
  AgentToolEditPreviewLine,
  AgentToolLocation,
} from "@cesium/core";
