// Moved to @cesium/core (packages/core/src/agent-chat.ts). Re-export shim keeps @/lib/agent-chat imports stable.
export {
  agentPermissionOptionsToUiChoices,
  buildConversationModeOptions,
  buildConversationModelOptions,
  buildDraftModeOptionsForBackend,
  buildDraftModelOptionsForBackend,
  goalProgressStatuses,
  dedupeAgentStoredEvents,
  extractComposerUserMessageHistory,
  extractLiveSubagentTranscriptFromMessages,
  findConversationModeConfigOption,
  findConversationModelConfigOption,
  getConversationLatestSeq,
  isAgentCesiumPauseDraining,
  isAgentCesiumTurnActive,
  isAgentConversationBusy,
  isAgentConversationPaused,
  isAgentTodoJsonArrayPayload,
  isAgentTodoJsonDetailString,
  isIncomingEventDroppedByAcpToolStrip,
  latestGoalProgressStatus,
  mergeAgentConversationStatusFromEvent,
  projectAgentEventsToChatMessages,
  resolveConversationModel,
  resolveDraftModelForBackend,
  stripAgentTodoJsonAssistantContent,
  stripSpuriousAcpToolCallReplays,
} from "@cesium/core";
export type {
  GoalProgressSnapshotStatus,
  GoalProgressStatus,
  ProjectAgentEventsOptions,
} from "@cesium/core";
