export {
  AURORA_BLUR_DEFAULT,
  AURORA_BLUR_MAX,
  AURORA_BLUR_MIN,
  AURORA_CONVERSATION_STATES,
  AURORA_INTENSITY_DEFAULT,
  AURORA_INTENSITY_MAX,
  AURORA_INTENSITY_MIN,
  AURORA_PRESETS,
  AURORA_PRESET_IDS,
  AURORA_SPEED_DEFAULT,
  AURORA_SPEED_MAX,
  AURORA_SPEED_MIN,
  DEFAULT_AURORA_CUSTOM_COLORS,
  auroraRgbToCss,
  auroraRgbToHex,
  createDefaultAuroraConfig,
  isAuroraConversationState,
  isAuroraPresetId,
  normalizeAuroraConfig,
  parseAuroraHex,
  resolveAuroraPresetColors,
  sanitizeAuroraCustomColors,
  sanitizeAuroraRgb,
} from "@cesium/client";
export type {
  AuroraConfig,
  AuroraConversationState,
  AuroraPresetDefinition,
  AuroraPresetId,
  AuroraRgb,
} from "@cesium/client";
