import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Bot,
  Blocks,
  Braces,
  Brackets,
  Container,
  Database,
  File,
  FileArchive,
  FileCode,
  FileImage,
  FileJson,
  FileText,
  GitBranch,
  GitPullRequest,
  Globe,
  KeyRound,
  Lock,
  Package,
  ScrollText,
  Settings,
  SquareCode,
  SwatchBook,
  Table,
  Terminal,
  Type,
  ListChecks,
} from "lucide-react";

export type FileTypeIconEntry = { Icon: LucideIcon; className: string };

/** Per-stack tints: mostly `FileCode` / `FileJson` / `Terminal` with readable contrast on dark UI. */
export const fileTypeIcons = {
  shell: { Icon: Terminal, className: "text-[#4ec9b0]" },
  powershell: { Icon: Terminal, className: "text-[#6caedd]" },
  makefile: { Icon: Terminal, className: "text-[#b8bb26]" },
  json: { Icon: FileJson, className: "text-[#d4c26d]" },
  jsonl: { Icon: FileJson, className: "text-[#b8c873]" },
  jupyter: { Icon: FileJson, className: "text-[#f37726]" },
  markdown: { Icon: FileText, className: "text-[#6cb5f5]" },
  typescript: { Icon: FileCode, className: "text-[#519aba]" },
  javascript: { Icon: FileCode, className: "text-[#d4c26d]" },
  css: { Icon: SwatchBook, className: "text-[#c678dd]" },
  html: { Icon: Globe, className: "text-[#e37933]" },
  yaml: { Icon: Brackets, className: "text-[#cb4f4f]" },
  toml: { Icon: Settings, className: "text-[#9a7dc2]" },
  xml: { Icon: Brackets, className: "text-[#cc8861]" },
  svg: { Icon: FileImage, className: "text-[#e2c08d]" },
  image: { Icon: FileImage, className: "text-[#9cdcfe]" },
  font: { Icon: Type, className: "text-[#b5cea8]" },
  sql: { Icon: Database, className: "text-[#ce9178]" },
  graphql: { Icon: SquareCode, className: "text-[#e535ab]" },
  prisma: { Icon: Database, className: "text-[#79b8ff]" },
  wasm: { Icon: Braces, className: "text-[#8064a9]" },
  archive: { Icon: FileArchive, className: "text-[#d4a520]" },
  log: { Icon: ScrollText, className: "text-[var(--text-secondary)]" },
  table: { Icon: Table, className: "text-[#6aab73]" },
  docker: { Icon: Container, className: "text-[#2496ed]" },
  git: { Icon: GitBranch, className: "text-[#f14e32]" },
  env: { Icon: KeyRound, className: "text-[#eec76a]" },
  npmPackage: { Icon: Package, className: "text-[#cc3e44]" },
  npmLock: { Icon: Lock, className: "text-[#7aadc9]" },
  readme: { Icon: BookOpen, className: "text-[#6cb5f5]" },
  toolchain: { Icon: Settings, className: "text-[#c9c9c9]" },
  proto: { Icon: SquareCode, className: "text-[#6fa8f5]" },
  terraform: { Icon: Brackets, className: "text-[#5c4ee5]" },
  tex: { Icon: FileText, className: "text-[#3e6118]" },
  diff: { Icon: FileText, className: "text-[#88c999]" },
  python: { Icon: FileCode, className: "text-[#4584b6]" },
  rust: { Icon: FileCode, className: "text-[#dea584]" },
  go: { Icon: FileCode, className: "text-[#29b6f6]" },
  javaFamily: { Icon: FileCode, className: "text-[#e76c74]" },
  csharp: { Icon: FileCode, className: "text-[#b393f6]" },
  fsharp: { Icon: FileCode, className: "text-[#378bba]" },
  cpp: { Icon: FileCode, className: "text-[#6699cc]" },
  cLang: { Icon: FileCode, className: "text-[#86b8c8]" },
  ruby: { Icon: FileCode, className: "text-[#cc342d]" },
  php: { Icon: FileCode, className: "text-[#8892bf]" },
  swift: { Icon: FileCode, className: "text-[#f77927]" },
  kotlin: { Icon: FileCode, className: "text-[#7f52ff]" },
  vue: { Icon: FileCode, className: "text-[#41b883]" },
  svelte: { Icon: FileCode, className: "text-[#ff3e00]" },
  zig: { Icon: FileCode, className: "text-[#f7a41d]" },
  asm: { Icon: FileCode, className: "text-[#9e9e9e]" },
  rLang: { Icon: FileCode, className: "text-[#2266b8]" },
  julia: { Icon: FileCode, className: "text-[#9558b2]" },
  matlab: { Icon: FileCode, className: "text-[#e16737]" },
  haskell: { Icon: FileCode, className: "text-[#5d4f85]" },
  scala: { Icon: FileCode, className: "text-[#dd0029]" },
  erlang: { Icon: FileCode, className: "text-[#a2003e]" },
  elixir: { Icon: FileCode, className: "text-[#6e4a7e]" },
  ocaml: { Icon: FileCode, className: "text-[#ec6813]" },
  objc: { Icon: FileCode, className: "text-[#438eff]" },
  arduino: { Icon: FileCode, className: "text-[#00979d]" },
  cobol: { Icon: FileCode, className: "text-[#3c86bc]" },
  lisp: { Icon: FileCode, className: "text-[#ccccff]" },
  scheme: { Icon: FileCode, className: "text-[#a5c8ff]" },
  racket: { Icon: FileCode, className: "text-[#cf5c65]" },
  clojure: { Icon: FileCode, className: "text-[#91dc51]" },
  crystal: { Icon: FileCode, className: "text-[#c8c8c8]" },
  dart: { Icon: FileCode, className: "text-[#39b4e8]" },
  nim: { Icon: FileCode, className: "text-[#ffc745]" },
  vlang: { Icon: FileCode, className: "text-[#5d87bf]" },
  hdl: { Icon: FileCode, className: "text-[#c9a227]" },
  fortran: { Icon: FileCode, className: "text-[#7349ac]" },
  ada: { Icon: FileCode, className: "text-[#02f88c]" },
  dlang: { Icon: FileCode, className: "text-[#b03931]" },
  lua: { Icon: FileCode, className: "text-[#8900ff]" },
  perl: { Icon: FileCode, className: "text-[#0298c3]" },
  groovy: { Icon: FileCode, className: "text-[#53a057]" },
  solidity: { Icon: FileCode, className: "text-[#aa6748]" },
  prolog: { Icon: FileCode, className: "text-[#e61b23]" },
  wasmText: { Icon: FileCode, className: "text-[#6565b8]" },
  batch: { Icon: Terminal, className: "text-[#c4c42c]" },
  csharpvb: { Icon: FileCode, className: "text-[#945bb3]" },
  cuda: { Icon: FileCode, className: "text-[#76b900]" },
  shader: { Icon: FileCode, className: "text-[#559cdb]" },
  ini: { Icon: Settings, className: "text-[#9da39a]" },
  mathematica: { Icon: FileCode, className: "text-[#dd1100]" },
  pascal: { Icon: FileCode, className: "text-[#e3b000]" },
  idris: { Icon: FileCode, className: "text-[#8b6ccc]" },
  lean: { Icon: FileCode, className: "text-[#1a76c5]" },
  agda: { Icon: FileCode, className: "text-[#7172c2]" },
  isabelle: { Icon: FileCode, className: "text-[#bf5a79]" },
  stan: { Icon: FileCode, className: "text-[#b71c1c]" },
  gleam: { Icon: FileCode, className: "text-[#ffaff3]" },
  purescript: { Icon: FileCode, className: "text-[#b4c7d9]" },
  coffeescript: { Icon: FileCode, className: "text-[#c5986b]" },
  default: { Icon: File, className: "text-[var(--text-secondary)]" },
  settings: { Icon: Settings, className: "text-[var(--text-secondary)]" },
  browser: { Icon: Globe, className: "text-[#6cb5f5]" },
  kanban: { Icon: Table, className: "text-[#6aab73]" },
  pullRequest: { Icon: GitPullRequest, className: "text-[#6cb5f5]" },
  plan: { Icon: ListChecks, className: "text-[var(--plan-accent)]" },
  extension: { Icon: Blocks, className: "text-[#c084fc]" },
  agent: { Icon: Bot, className: "text-[var(--accent)]" },
  subagent: { Icon: Bot, className: "text-[#c084fc]" },
} as const satisfies Record<string, FileTypeIconEntry>;

export type FileTypeIconKind = keyof typeof fileTypeIcons;
