import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Bot,
  Braces,
  Brackets,
  Container,
  Database,
  File,
  FileArchive,
  FileCode,
  FileImage,
  FileJson,
  FileText,
  GitBranch,
  Globe,
  KeyRound,
  Lock,
  Package,
  ScrollText,
  Settings,
  SquareCode,
  SwatchBook,
  Table,
  Terminal,
  Type,
} from "lucide-react";

export type FileTypeIconEntry = { Icon: LucideIcon; className: string };

/** Per-stack tints: mostly `FileCode` / `FileJson` / `Terminal` with readable contrast on dark UI. */
export const fileTypeIcons = {
  shell: { Icon: Terminal, className: "text-[#4ec9b0]" },
  powershell: { Icon: Terminal, className: "text-[#6caedd]" },
  makefile: { Icon: Terminal, className: "text-[#b8bb26]" },
  json: { Icon: FileJson, className: "text-[#d4c26d]" },
  jsonl: { Icon: FileJson, className: "text-[#b8c873]" },
  jupyter: { Icon: FileJson, className: "text-[#f37726]" },
  markdown: { Icon: FileText, className: "text-[#6cb5f5]" },
  typescript: { Icon: FileCode, className: "text-[#519aba]" },
  javascript: { Icon: FileCode, className: "text-[#d4c26d]" },
  css: { Icon: SwatchBook, className: "text-[#c678dd]" },
  html: { Icon: Globe, className: "text-[#e37933]" },
  yaml: { Icon: Brackets, className: "text-[#cb4f4f]" },
  toml: { Icon: Settings, className: "text-[#9a7dc2]" },
  xml: { Icon: Brackets, className: "text-[#cc8861]" },
  svg: { Icon: FileImage, className: "text-[#e2c08d]" },
  image: { Icon: FileImage, className: "text-[#9cdcfe]" },
  font: { Icon: Type, className: "text-[#b5cea8]" },
  sql: { Icon: Database, className: "text-[#ce9178]" },
  graphql: { Icon: SquareCode, className: "text-[#e535ab]" },
  prisma: { Icon: Database, className: "text-[#79b8ff]" },
  wasm: { Icon: Braces, className: "text-[#8064a9]" },
  archive: { Icon: FileArchive, className: "text-[#d4a520]" },
  log: { Icon: ScrollText, className: "text-[var(--text-secondary)]" },
  table: { Icon: Table, className: "text-[#6aab73]" },
  docker: { Icon: Container, className: "text-[#2496ed]" },
  git: { Icon: GitBranch, className: "text-[#f14e32]" },
  env: { Icon: KeyRound, className: "text-[#eec76a]" },
  npmPackage: { Icon: Package, className: "text-[#cc3e44]" },
  npmLock: { Icon: Lock, className: "text-[#7aadc9]" },
  readme: { Icon: BookOpen, className: "text-[#6cb5f5]" },
  toolchain: { Icon: Settings, className: "text-[#c9c9c9]" },
  proto: { Icon: SquareCode, className: "text-[#6fa8f5]" },
  terraform: { Icon: Brackets, className: "text-[#5c4ee5]" },
  tex: { Icon: FileText, className: "text-[#3e6118]" },
  diff: { Icon: FileText, className: "text-[#88c999]" },
  python: { Icon: FileCode, className: "text-[#4584b6]" },
  rust: { Icon: FileCode, className: "text-[#dea584]" },
  go: { Icon: FileCode, className: "text-[#29b6f6]" },
  javaFamily: { Icon: FileCode, className: "text-[#e76c74]" },
  csharp: { Icon: FileCode, className: "text-[#b393f6]" },
  fsharp: { Icon: FileCode, className: "text-[#378bba]" },
  cpp: { Icon: FileCode, className: "text-[#6699cc]" },
  cLang: { Icon: FileCode, className: "text-[#86b8c8]" },
  ruby: { Icon: FileCode, className: "text-[#cc342d]" },
  php: { Icon: FileCode, className: "text-[#8892bf]" },
  swift: { Icon: FileCode, className: "text-[#f77927]" },
  kotlin: { Icon: FileCode, className: "text-[#7f52ff]" },
  vue: { Icon: FileCode, className: "text-[#41b883]" },
  svelte: { Icon: FileCode, className: "text-[#ff3e00]" },
  zig: { Icon: FileCode, className: "text-[#f7a41d]" },
  asm: { Icon: FileCode, className: "text-[#9e9e9e]" },
  rLang: { Icon: FileCode, className: "text-[#2266b8]" },
  julia: { Icon: FileCode, className: "text-[#9558b2]" },
  matlab: { Icon: FileCode, className: "text-[#e16737]" },
  haskell: { Icon: FileCode, className: "text-[#5d4f85]" },
  scala: { Icon: FileCode, className: "text-[#dd0029]" },
  erlang: { Icon: FileCode, className: "text-[#a2003e]" },
  elixir: { Icon: FileCode, className: "text-[#6e4a7e]" },
  ocaml: { Icon: FileCode, className: "text-[#ec6813]" },
  objc: { Icon: FileCode, className: "text-[#438eff]" },
  arduino: { Icon: FileCode, className: "text-[#00979d]" },
  cobol: { Icon: FileCode, className: "text-[#3c86bc]" },
  lisp: { Icon: FileCode, className: "text-[#ccccff]" },
  scheme: { Icon: FileCode, className: "text-[#a5c8ff]" },
  racket: { Icon: FileCode, className: "text-[#cf5c65]" },
  clojure: { Icon: FileCode, className: "text-[#91dc51]" },
  crystal: { Icon: FileCode, className: "text-[#c8c8c8]" },
  dart: { Icon: FileCode, className: "text-[#39b4e8]" },
  nim: { Icon: FileCode, className: "text-[#ffc745]" },
  vlang: { Icon: FileCode, className: "text-[#5d87bf]" },
  hdl: { Icon: FileCode, className: "text-[#c9a227]" },
  fortran: { Icon: FileCode, className: "text-[#7349ac]" },
  ada: { Icon: FileCode, className: "text-[#02f88c]" },
  dlang: { Icon: FileCode, className: "text-[#b03931]" },
  lua: { Icon: FileCode, className: "text-[#8900ff]" },
  perl: { Icon: FileCode, className: "text-[#0298c3]" },
  groovy: { Icon: FileCode, className: "text-[#53a057]" },
  solidity: { Icon: FileCode, className: "text-[#aa6748]" },
  prolog: { Icon: FileCode, className: "text-[#e61b23]" },
  wasmText: { Icon: FileCode, className: "text-[#6565b8]" },
  batch: { Icon: Terminal, className: "text-[#c4c42c]" },
  csharpvb: { Icon: FileCode, className: "text-[#945bb3]" },
  cuda: { Icon: FileCode, className: "text-[#76b900]" },
  shader: { Icon: FileCode, className: "text-[#559cdb]" },
  ini: { Icon: Settings, className: "text-[#9da39a]" },
  mathematica: { Icon: FileCode, className: "text-[#dd1100]" },
  pascal: { Icon: FileCode, className: "text-[#e3b000]" },
  idris: { Icon: FileCode, className: "text-[#8b6ccc]" },
  lean: { Icon: FileCode, className: "text-[#1a76c5]" },
  agda: { Icon: FileCode, className: "text-[#7172c2]" },
  isabelle: { Icon: FileCode, className: "text-[#bf5a79]" },
  stan: { Icon: FileCode, className: "text-[#b71c1c]" },
  gleam: { Icon: FileCode, className: "text-[#ffaff3]" },
  purescript: { Icon: FileCode, className: "text-[#b4c7d9]" },
  coffeescript: { Icon: FileCode, className: "text-[#c5986b]" },
  default: { Icon: File, className: "text-[var(--text-secondary)]" },
  settings: { Icon: Settings, className: "text-[var(--text-secondary)]" },
  browser: { Icon: Globe, className: "text-[#6cb5f5]" },
  subagent: { Icon: Bot, className: "text-[#c084fc]" },
} as const satisfies Record<string, FileTypeIconEntry>;

export type FileTypeIconKind = keyof typeof fileTypeIcons;

const LANG_ALIASES: Record<string, FileTypeIconKind> = {
  ts: "typescript",
  typescript: "typescript",
  js: "javascript",
  javascript: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  css: "css",
  scss: "css",
  less: "css",
  sass: "css",
  json: "json",
  jsonl: "jsonl",
  jsonlines: "jsonl",
  ndjson: "jsonl",
  md: "markdown",
  markdown: "markdown",
  mdx: "markdown",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  html: "html",
  svg: "svg",
  sql: "sql",
  shell: "shell",
  bash: "shell",
  sh: "shell",
  zsh: "shell",
  fish: "shell",
  powershell: "powershell",
  pwsh: "powershell",
  python: "python",
  py: "python",
  rust: "rust",
  rs: "rust",
  go: "go",
  golang: "go",
  java: "javaFamily",
  jvm: "javaFamily",
  kotlin: "kotlin",
  kt: "kotlin",
  kts: "kotlin",
  cs: "csharp",
  csharp: "csharp",
  cpp: "cpp",
  cxx: "cpp",
  "c++": "cpp",
  cc: "cpp",
  c: "cLang",
  h: "cLang",
  rb: "ruby",
  ruby: "ruby",
  php: "php",
  swift: "swift",
  vue: "vue",
  svelte: "svelte",
  prisma: "prisma",
  graphql: "graphql",
  gql: "graphql",
  zig: "zig",
  wasm: "wasm",
  nasm: "asm",
  asm: "asm",
  assembly: "asm",
  r: "rLang",
  rl: "rLang",
  rlang: "rLang",
  julia: "julia",
  jl: "julia",
  matlab: "matlab",
  octave: "matlab",
  haskell: "haskell",
  hs: "haskell",
  scala: "scala",
  erlang: "erlang",
  elixir: "elixir",
  ex: "elixir",
  ocaml: "ocaml",
  ml: "ocaml",
  objc: "objc",
  "objective-c": "objc",
  arduino: "arduino",
  cobol: "cobol",
  lisp: "lisp",
  scheme: "scheme",
  racket: "racket",
  clojure: "clojure",
  crystal: "crystal",
  dart: "dart",
  nim: "nim",
  verilog: "hdl",
  vhdl: "hdl",
  systemverilog: "hdl",
  v: "vlang",
  fortran: "fortran",
  fsharp: "fsharp",
  fs: "fsharp",
  ada: "ada",
  d: "dlang",
  dlang: "dlang",
  lua: "lua",
  perl: "perl",
  groovy: "groovy",
  solidity: "solidity",
  prolog: "prolog",
  terraform: "terraform",
  hcl: "terraform",
  cuda: "cuda",
  metal: "shader",
  hlsl: "shader",
  glsl: "shader",
  mathematica: "mathematica",
  wolfram: "mathematica",
  protobuf: "proto",
  capnproto: "proto",
  awk: "perl",
  sed: "shell",
  bat: "batch",
  cmd: "batch",
  ini: "ini",
  vb: "csharpvb",
  "vb.net": "csharpvb",
  tex: "tex",
  latex: "tex",
  dockerfile: "docker",
  jupyter: "jupyter",
  ipynb: "jupyter",
  idris: "idris",
  lean: "lean",
  agda: "agda",
  isabelle: "isabelle",
  pascal: "pascal",
  delphi: "pascal",
  stan: "stan",
  vlang: "vlang",
  gleam: "gleam",
  purescript: "purescript",
  coffeescript: "coffeescript",
  coffee: "coffeescript",
};

/** Exact basename (lowercase). */
const EXACT_NAME: Record<string, FileTypeIconKind> = {
  ".env": "env",
  ".env.local": "env",
  ".env.development": "env",
  ".env.production": "env",
  ".env.test": "env",
  ".env.example": "env",
  ".env.defaults": "env",
  ".env.sample": "env",
  ".gitignore": "git",
  ".gitattributes": "git",
  ".gitmodules": "git",
  ".mailmap": "git",
  "package.json": "npmPackage",
  "package-lock.json": "npmLock",
  "npm-shrinkwrap.json": "npmLock",
  "yarn.lock": "npmLock",
  "pnpm-lock.yaml": "npmLock",
  "pnpm-workspace.yaml": "npmPackage",
  "bun.lockb": "npmLock",
  "readme.md": "readme",
  "readme.txt": "readme",
  "readme": "readme",
  "changelog.md": "readme",
  "changelog": "readme",
  "contributing.md": "readme",
  "code_of_conduct.md": "readme",
  "security.md": "readme",
  "license": "readme",
  "license.md": "readme",
  "copying": "readme",
  "dockerfile": "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  "compose.yml": "docker",
  "compose.yaml": "docker",
  ".dockerignore": "docker",
  "makefile": "makefile",
  "gnumakefile": "makefile",
  "cmakelists.txt": "toolchain",
};

function looksLikeToolchainConfig(fileName: string): boolean {
  const lower = fileName.toLowerCase();
  if (/^tsconfig(\..*)?\.json$/.test(lower)) return true;
  if (/^jsconfig\.json$/.test(lower)) return true;
  if (lower === "components.json") return true;
  if (/^eslint\.config\./.test(lower)) return true;
  if (/^\.eslintrc/.test(lower)) return true;
  if (/^\.prettierrc/.test(lower)) return true;
  if (/^prettier\.config\./.test(lower)) return true;
  if (/^(postcss|tailwind|vite|vitest|rollup|webpack)\.config\./.test(lower))
    return true;
  if (/^(next|nuxt|svelte|astro)\.config\./.test(lower)) return true;
  if (/^babel\.config\./.test(lower)) return true;
  if (/^playwright\.config\./.test(lower)) return true;
  if (/^jest\.config\./.test(lower)) return true;
  if (/^vitest\.config\./.test(lower)) return true;
  if (/^\.(npmrc|yarnrc|yarnrc\.yml|pnpmrc|nvmrc|node-version|babelrc|browserslistrc)$/i.test(lower))
    return true;
  if (lower === ".editorconfig") return true;
  if (lower === ".cursorrules" || lower.endsWith(".cursorrules")) return true;
  if (lower === "next-env.d.ts") return false;
  return false;
}

function isEnvFile(fileName: string): boolean {
  const lower = fileName.toLowerCase();
  if (lower === ".env" || lower.startsWith(".env.")) return true;
  if (lower.startsWith(".envrc")) return true;
  return false;
}

const EXT_TO_KIND: Record<string, FileTypeIconKind> = {
  ".ts": "typescript",
  ".tsx": "typescript",
  ".mts": "typescript",
  ".cts": "typescript",
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".css": "css",
  ".scss": "css",
  ".less": "css",
  ".sass": "css",
  ".pcss": "css",
  ".json": "json",
  ".jsonc": "json",
  ".jsonl": "jsonl",
  ".ndjson": "jsonl",
  ".json-seq": "jsonl",
  ".md": "markdown",
  ".mdx": "markdown",
  ".mdc": "markdown",
  ".rst": "markdown",
  ".adoc": "markdown",
  ".asciidoc": "markdown",
  ".ipynb": "jupyter",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".ksh": "shell",
  ".fish": "shell",
  ".ps1": "powershell",
  ".psm1": "powershell",
  ".psd1": "powershell",
  ".ps1xml": "powershell",
  ".psc1": "powershell",
  ".html": "html",
  ".htm": "html",
  ".xhtml": "html",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".xml": "xml",
  ".xsl": "xml",
  ".xsd": "xml",
  ".rss": "xml",
  ".plist": "xml",
  ".svg": "svg",
  ".sql": "sql",
  ".ddl": "sql",
  ".mysql": "sql",
  ".pgsql": "sql",
  ".py": "python",
  ".pyw": "python",
  ".pyi": "python",
  ".pyx": "python",
  ".rs": "rust",
  ".go": "go",
  ".java": "javaFamily",
  ".jsp": "javaFamily",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".cs": "csharp",
  ".csx": "csharp",
  ".vb": "csharpvb",
  ".fs": "fsharp",
  ".fsi": "fsharp",
  ".fsx": "fsharp",
  ".fsproj": "fsharp",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".hh": "cpp",
  ".ixx": "cpp",
  ".mm": "cpp",
  ".c": "cLang",
  ".h": "cLang",
  ".rb": "ruby",
  ".erb": "ruby",
  ".rake": "ruby",
  ".gemspec": "ruby",
  ".php": "php",
  ".phtml": "php",
  ".swift": "swift",
  ".vue": "vue",
  ".svelte": "svelte",
  ".prisma": "prisma",
  ".graphql": "graphql",
  ".gql": "graphql",
  ".wasm": "wasm",
  ".wat": "wasmText",
  ".wast": "wasmText",
  ".png": "image",
  ".jpg": "image",
  ".jpeg": "image",
  ".gif": "image",
  ".webp": "image",
  ".ico": "image",
  ".bmp": "image",
  ".avif": "image",
  ".tiff": "image",
  ".heic": "image",
  ".woff": "font",
  ".woff2": "font",
  ".ttf": "font",
  ".otf": "font",
  ".eot": "font",
  ".log": "log",
  ".csv": "table",
  ".tsv": "table",
  ".ssv": "table",
  ".zip": "archive",
  ".tar": "archive",
  ".gz": "archive",
  ".tgz": "archive",
  ".bz2": "archive",
  ".xz": "archive",
  ".7z": "archive",
  ".rar": "archive",
  ".tsbuildinfo": "json",
  ".zig": "zig",
  ".zon": "zig",
  ".asm": "asm",
  ".s": "asm",
  ".inc": "asm",
  ".nasm": "asm",
  ".r": "rLang",
  ".jl": "julia",
  ".mlx": "matlab",
  ".m": "objc",
  ".mat": "matlab",
  ".hs": "haskell",
  ".lhs": "haskell",
  ".cabal": "haskell",
  ".hs-boot": "haskell",
  ".scala": "scala",
  ".sc": "scala",
  ".erl": "erlang",
  ".hrl": "erlang",
  ".ex": "elixir",
  ".exs": "elixir",
  ".eex": "elixir",
  ".heex": "elixir",
  ".leex": "elixir",
  ".ml": "ocaml",
  ".mli": "ocaml",
  ".mll": "ocaml",
  ".mly": "ocaml",
  ".ino": "arduino",
  ".pde": "arduino",
  ".cob": "cobol",
  ".cbl": "cobol",
  ".cpy": "cobol",
  ".cobol": "cobol",
  ".lisp": "lisp",
  ".lsp": "lisp",
  ".scpt": "lisp",
  ".scm": "scheme",
  ".ss": "scheme",
  ".rkt": "racket",
  ".clj": "clojure",
  ".cljs": "clojure",
  ".cljc": "clojure",
  ".edn": "clojure",
  ".cr": "crystal",
  ".dart": "dart",
  ".nim": "nim",
  ".nims": "nim",
  ".nimble": "nim",
  ".v": "hdl",
  ".sv": "hdl",
  ".svh": "hdl",
  ".vh": "hdl",
  ".vhd": "hdl",
  ".vhdl": "hdl",
  ".f90": "fortran",
  ".f95": "fortran",
  ".f03": "fortran",
  ".f08": "fortran",
  ".f": "fortran",
  ".for": "fortran",
  ".f77": "fortran",
  ".adb": "ada",
  ".ads": "ada",
  ".d": "dlang",
  ".di": "dlang",
  ".lua": "lua",
  ".luau": "lua",
  ".pl": "perl",
  ".pm": "perl",
  ".t": "perl",
  ".pod": "perl",
  ".awk": "perl",
  ".groovy": "groovy",
  ".gvy": "groovy",
  ".gradle": "groovy",
  ".sol": "solidity",
  ".proto": "proto",
  ".capnp": "proto",
  ".thrift": "proto",
  ".tf": "terraform",
  ".tfvars": "terraform",
  ".hcl": "terraform",
  ".pas": "pascal",
  ".pp": "pascal",
  ".dpr": "pascal",
  ".pro": "prolog",
  ".P": "prolog",
  ".tex": "tex",
  ".sty": "tex",
  ".cls": "tex",
  ".bib": "tex",
  ".ltx": "tex",
  ".cu": "cuda",
  ".cuh": "cuda",
  ".metal": "shader",
  ".hlsl": "shader",
  ".hlsli": "shader",
  ".glsl": "shader",
  ".vert": "shader",
  ".frag": "shader",
  ".geom": "shader",
  ".comp": "shader",
  ".tese": "shader",
  ".tesc": "shader",
  ".wgsl": "shader",
  ".bat": "batch",
  ".cmd": "batch",
  ".ini": "ini",
  ".cfg": "ini",
  ".cnf": "ini",
  ".properties": "ini",
  ".editorconfig": "ini",
  ".wl": "mathematica",
  ".wls": "mathematica",
  ".nb": "mathematica",
  ".rmd": "rLang",
  ".q": "rLang",
  ".idr": "idris",
  ".lean": "lean",
  ".agda": "agda",
  ".thy": "isabelle",
  ".stan": "stan",
  ".vim": "shell",
  ".vimrc": "shell",
  ".el": "lisp",
  ".emacs": "shell",
  ".diff": "diff",
  ".patch": "diff",
  ".coffee": "coffeescript",
  ".litcoffee": "coffeescript",
  ".purs": "purescript",
  ".gleam": "gleam",
};

function declarationFileKind(fileName: string): FileTypeIconKind | null {
  const lower = fileName.toLowerCase();
  if (
    lower.endsWith(".d.ts") ||
    lower.endsWith(".d.mts") ||
    lower.endsWith(".d.cts")
  ) {
    return "typescript";
  }
  return null;
}

function resolveKind(language: string | undefined, fileName: string): FileTypeIconKind {
  const base = fileName.includes("/")
    ? fileName.slice(fileName.lastIndexOf("/") + 1)
    : fileName;
  const lowerBase = base.toLowerCase();

  const exact = EXACT_NAME[lowerBase];
  if (exact) return exact;

  if (looksLikeToolchainConfig(base)) return "toolchain";

  if (isEnvFile(base)) return "env";

  const decl = declarationFileKind(base);
  if (decl) return decl;

  const norm = language?.toLowerCase().trim();
  if (norm) {
    const fromAlias = LANG_ALIASES[norm];
    if (fromAlias) return fromAlias;
  }

  const dot = base.lastIndexOf(".");
  if (dot >= 0) {
    const ext = base.slice(dot).toLowerCase();
    const fromExt = EXT_TO_KIND[ext];
    if (fromExt) return fromExt;
  }

  return "default";
}

/** Uses `language` when set, then basename rules and file extension. */
export function getFileIconForNode(
  language: string | undefined,
  fileName: string
): FileTypeIconEntry {
  return fileTypeIcons[resolveKind(language, fileName)];
}

