// Moved to @cesium/client (packages/client/src/global-settings.ts). Re-export shim keeps existing imports stable.
export {
  DEFAULT_CMD_TAGS,
  DEFAULT_MODE_TAGS,
  createDefaultGlobalSettings,
  normalizeLoadedGlobalSettings,
  applyAgentRailViewPreset,
  matchingAgentRailViewPreset,
} from "@cesium/client";
export type {
  AgentRailGroupByMode,
  AgentRailOrderByMode,
  AgentRailScope,
  AgentRailSectionId,
  AgentRailSettingsState,
  AgentRailViewPreset,
  AgentsSettingsState,
  ChatFolderState,
  FeaturesSettingsState,
  GeneralSettingsState,
  GlobalAppSettingsSlice,
  GlobalSettingsState,
  ModelToggleState,
  ModelsSettingsState,
  NewChatWidgetId,
  NewChatWidgetsState,
  RememberedAgentPermissionRule,
  ServerRailAppearance,
  ToolsSettingsState,
  WorkspaceRailAppearance,
  WorkspaceSortMode,
} from "@cesium/client";
export {
  AGENT_RAIL_GROUP_BY_LABELS,
  AGENT_RAIL_GROUP_BY_MODES,
  AGENT_RAIL_ORDER_BY_LABELS,
  AGENT_RAIL_ORDER_BY_MODES,
  AGENT_RAIL_SECTION_IDS,
  AGENT_RAIL_VIEW_PRESETS,
  AGENT_RAIL_VIEW_PRESET_INFO,
  NEW_CHAT_WIDGET_IDS,
  createDefaultNewChatWidgetsState,
  isNewChatWidgetId,
  normalizeNewChatWidgetsState,
} from "@cesium/client";
export {
  DEVICE_PICKER_ACTION_IDS,
  DEVICE_PICKER_ACTION_LABELS,
  DEVICE_PICKER_SECTION_IDS,
  DEVICE_PICKER_SECTION_LABELS,
  createDefaultDevicePickerState,
  devicePickerCodespaceEntryId,
  devicePickerSectionHiddenId,
  devicePickerServerEntryId,
  isDevicePickerActionId,
  isDevicePickerEntryHidden,
  isDevicePickerSectionHidden,
  isDevicePickerSectionId,
  moveDevicePickerEntry,
  moveDevicePickerSection,
  normalizeDevicePickerState,
  sortByDevicePickerOrder,
  toggleDevicePickerHidden,
} from "@cesium/client";
export type {
  DevicePickerActionId,
  DevicePickerSectionId,
  DevicePickerState,
} from "@cesium/client";
export {
  AURORA_MAX_CUSTOM_COLORS,
  AURORA_MIN_CUSTOM_COLORS,
  AURORA_PLACEMENT_IDS,
  AURORA_PLACEMENT_LABELS,
  AURORA_PRESET_CATALOG,
  AURORA_PRESET_IDS,
  DEFAULT_AURORA_PRESET_ID,
  createDefaultAuroraSettings,
  isAuroraPlacementId,
  isAuroraPresetId,
  normalizeAuroraSettings,
  resolveAuroraColors,
} from "@cesium/client";
export type {
  AuroraPlacementId,
  AuroraPresetDefinition,
  AuroraPresetId,
  AuroraSettingsState,
} from "@cesium/client";
