// Moved to @cesium/client (packages/client/src/keyboard-shortcuts.ts). Re-export shim keeps existing imports stable.
export {
  DEFAULT_KEYBOARD_SHORTCUT_BINDINGS,
  SHORTCUT_COMMAND_DEFINITIONS,
  createDefaultKeyboardShortcutsState,
  detectShortcutPlatform,
  eventMatchesAgentSwitcherChord,
  eventMatchesShortcutCommand,
  formatShortcutBinding,
  formatShortcutBindings,
  formatShortcutBindingsForInput,
  getShortcutBindingsForCommand,
  getShortcutCommandDefinition,
  getShortcutDisplayForCommand,
  isEditableShortcutTarget,
  isNativeEditableShortcutEvent,
  matchesShortcutStep,
  normalizeKeyForCapture,
  normalizeKeyboardShortcutsState,
  normalizeShortcutBinding,
  normalizeShortcutBindingsList,
  normalizeShortcutBindingsMap,
  parseShortcutBinding,
  parseShortcutBindingsInput,
  primaryModifierLabel,
  tryDispatchKeyboardShortcut,
} from "@cesium/client";
export type {
  KeyboardShortcutBindingsMap,
  KeyboardShortcutsSettingsState,
  ParsedShortcutStep,
  ShortcutChordState,
  ShortcutCommandDefinition,
  ShortcutCommandSection,
  ShortcutPlatform,
  VoiceInputMode,
} from "@cesium/client";
