// Moved to @cesium/client (packages/client/src/server-connections.ts). Re-export shim keeps existing imports stable.
export {
  SERVER_CONNECTIONS_EVENT,
  SERVER_CONNECTIONS_STORAGE_KEY,
  applyServerUrlBootstrap,
  bootstrapStoredServerConnection,
  createDefaultServerConnectionsState,
  createServerConnection,
  getActiveServerBaseUrl,
  getActiveServerConnection,
  getActiveServerStorageKey,
  getServerConnectionKey,
  getSettingsServerConnection,
  markServerConnectionUsed,
  mergeServerConnectionBootstrap,
  normalizeServerBaseUrl,
  normalizeServerConnectionsState,
  readStoredServerConnectionsState,
  removeServerConnection,
  requiresDefaultServerSelection,
  setDefaultServerConnection,
  shouldApplyServerUrlFromSearch,
  upsertServerConnection,
  writeStoredServerConnectionsState,
} from "@cesium/client";
export type {
  ServerConnection,
  ServerConnectionBootstrapOptions,
  ServerConnectionsState,
} from "@cesium/client";
