// Moved to @cesium/core (packages/core/src/types.ts). Re-export shim keeps @/lib/types imports stable.
export type {
  AgentModeOption,
  AgentTabIndicatorByConversationId,
  AskQuestionOption,
  AskQuestionStep,
  ChatMessage,
  ChatMessageType,
  ChatTab,
  EditorMode,
  EditorTab,
  ExplorerOpenRequest,
  FileNode,
  FileWatcherEvent,
  GitBranchInfo,
  GitWorkspaceStatus,
  GitWorktreeInfo,
  GitWorktreeSetupResult,
  ImageAttachment,
  ImageAttachmentState,
  KnownEditorMode,
  ModelInfo,
  PermissionChoiceOption,
  PlanBuildHandoff,
  QueuedChatPrompt,
  QueuedPromptConfigOverride,
  TerminalInfo,
  TodoItem,
  UserMessageSegment,
  WorkedSessionEditPreview,
  WorkedSessionEditPreviewLine,
  WorkedSessionEntry,
  WorkspaceInfo,
  WorkspaceKind,
  WorkspaceRecord,
  WorkspaceWindowRecord,
} from "@cesium/core";
export { isStandaloneChatWorkspace } from "@cesium/core";
