// Moved to @cesium/client (packages/client/src/workspace-session.ts). Re-export shim keeps existing imports stable.
export {
  AGENT_NEW_CHAT_SESSION_ID,
  WORKBENCH_LEGACY_SETTINGS_TAB_ID,
  createDefaultWorkspaceSession,
  createEmptyAgentSidePaneSession,
  createEmptyEditorSession,
  createPersistableWorkspaceSession,
  getAgentSidePaneSessionScopeId,
  getPersistedChatScrollTop,
  getWorkspaceChatScrollScopeId,
  mergeWorkspaceSessionFromImport,
  normalizeSettingsViewSession,
  persistChatScrollOverlay,
  resolvePersistedChatScroll,
  resolvePersistedChatScrollTop,
  writeChatScrollOverlayEntry,
} from "@cesium/client";
export type {
  AgentSidePaneSessionState,
  AgentViewSessionState,
  ChatScrollAnchor,
  ChatScrollOverlayEntry,
  ChatSessionState,
  EditorLayoutNode,
  EditorPaneId,
  EditorPaneState,
  EditorSessionState,
  EditorSplitOrientation,
  EditorStripItem,
  EditorTabGroupState,
  ExplorerSessionState,
  LayoutSessionState,
  MobilePanel,
  ResolvedChatScroll,
  SettingsPanelSearchFocus,
  SettingsViewSessionState,
  SidebarView,
  WorkbenchShellNonSettingsView,
  WorkbenchShellView,
  WorkspaceSessionState,
} from "@cesium/client";
