import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  // Patterns must be recursive (**/) so nested workspace build output
  // (apps/web/.next, apps/desktop/out, apps/*/dist, android intermediates)
  // is excluded; linting those took minutes and produced nothing.
  globalIgnores([
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/dist/**",
    ".docker/**",
    ".tmp/**",
    "**/next-env.d.ts",
    "**/public/**",
    "apps/mobile/android/**",
    "apps/desktop/.server-runtime/**",
    // Convex codegen output (regenerated by `npx convex dev` / codegen).
    "convex/_generated/**",
  ]),
  {
    rules: {
      // Legitimate patterns (refs mirroring props, hydration from storage, reset-on-open) are flagged;
      // disabling keeps `npm run lint` usable without rewriting half the tree.
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/refs": "off",
    },
  },
  {
    // Browser-side code must never block on native `alert` / `confirm` /
    // `prompt`: they look foreign, cannot be styled, break on Electron and
    // WebView shells, and stall the whole event loop. Use `useWorkbenchDialogs()`
    // from `@/components/dialogs/WorkbenchDialogProvider` instead.
    files: [
      "src/**",
      "apps/web/src/**",
      "apps/desktop-renderer/src/**",
      "apps/mobile/src/**",
      "packages/ui-web/src/**",
    ],
    rules: {
      "no-restricted-globals": [
        "error",
        {
          name: "alert",
          message: "Use useWorkbenchDialogs().alert() instead of the native alert().",
        },
        {
          name: "confirm",
          message: "Use useWorkbenchDialogs().confirm() instead of the native confirm().",
        },
        {
          name: "prompt",
          message: "Use useWorkbenchDialogs().prompt() instead of the native prompt().",
        },
      ],
      "no-restricted-properties": [
        "error",
        ...["window", "globalThis", "self"].flatMap((object) => [
          {
            object,
            property: "alert",
            message: "Use useWorkbenchDialogs().alert() instead of the native alert().",
          },
          {
            object,
            property: "confirm",
            message: "Use useWorkbenchDialogs().confirm() instead of the native confirm().",
          },
          {
            object,
            property: "prompt",
            message: "Use useWorkbenchDialogs().prompt() instead of the native prompt().",
          },
        ]),
      ],
    },
  },
  {
    // Node-side code: React hook naming/call rules don't apply outside React trees.
    files: ["server/**", "scripts/**", "apps/desktop/src/**", "apps/mobile/scripts/**"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },
  {
    // CommonJS by definition; `require()` is the import mechanism.
    // metro-transformer.js is also a Metro worker entry that must use require()
    // to load non-exported internals via absolute paths.
    files: ["**/*.cjs", "**/metro.config.js", "**/metro-transformer.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;
