import type {
  AgentBackendId,
  AgentProviderCapabilities,
} from "./types.js";

export const AGENT_CAPABILITY_KEYS = [
  "supportsLoadSession",
  "supportsModeSelection",
  "supportsModelSelection",
  "supportsSlashCommands",
  "supportsPermissions",
  "supportsToolCalls",
  "supportsStructuredPlans",
  "supportsTodos",
  "supportsSessionResume",
  "supportsPromptImages",
  "supportsInlineReasoning",
  "supportsCompletionRetry",
  "supportsCloudExecution",
  "supportsSideChats",
  "supportsCancelResume",
] as const satisfies readonly (keyof AgentProviderCapabilities)[];

/**
 * Single source of truth for each backend's advertised capabilities. Kept in
 * `agent-contract.ts` (which only imports types) so `providers.ts` and the
 * individual provider modules can read static metadata without pulling in the
 * heavy provider SDKs at process load.
 */
export const AGENT_CAPABILITIES: Record<AgentBackendId, AgentProviderCapabilities> = {
  "cesium-agent": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: false,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: true,
    supportsCloudExecution: false,
    supportsSideChats: true,
    supportsCancelResume: false,
  },
  "cursor-sdk": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: false,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    // The @cursor/sdk Agent API runs the same conversation contract on
    // Cursor-hosted cloud VMs (`Agent.create({ cloud })`).
    supportsCloudExecution: true,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "cursor-acp": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    // Cursor CLI over ACP runs locally; cloud execution is the SDK path.
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "opencode-server": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "opencode-v2-beta": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: false,
    supportsTodos: false,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "devin-acp": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "grok-build": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "codex-app-server": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: true,
  },
  "codex-acp": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "claude-code-sdk": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    // Streaming-input sessions accept Anthropic image blocks inline.
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "pi-agent": {
    supportsLoadSession: true,
    supportsModeSelection: false,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    // Extension `ctx.ui.confirm()` dialogs and the optional Cesium tool
    // approval gate both surface as permission cards.
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: false,
    supportsTodos: false,
    supportsSessionResume: true,
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: true,
  },
  "google-antigravity-cli": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    supportsPromptImages: false,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
  "google-antigravity-acp": {
    supportsLoadSession: true,
    supportsModeSelection: true,
    supportsModelSelection: true,
    supportsSlashCommands: true,
    supportsPermissions: true,
    supportsToolCalls: true,
    supportsStructuredPlans: true,
    supportsTodos: true,
    supportsSessionResume: true,
    // The official ACP server advertises promptCapabilities.image/audio/embeddedContext.
    supportsPromptImages: true,
    supportsInlineReasoning: true,
    supportsCompletionRetry: false,
    supportsCloudExecution: false,
    supportsSideChats: false,
    supportsCancelResume: false,
  },
};

export const AGENT_STORED_EVENT_KINDS = [
  "user_message",
  "system_reminder",
  "assistant_message_chunk",
  "assistant_message_end",
  "reasoning",
  "tool_call",
  "tool_call_update",
  "plan",
  "plan_file",
  "subagent",
  "question",
  "compression_summary",
  "permission_request",
  "permission_resolved",
  "system",
  "status",
  "agent_handoff",
  "chat_fork",
] as const;

export type AgentStoredEventKind = (typeof AGENT_STORED_EVENT_KINDS)[number];

export type BackendHarnessExpectation = {
  /**
   * Canonical event kinds the backend is expected to be able to emit when its
   * advertised capabilities are exercised. This is intentionally broader than a
   * single smoke turn and is used as a fixture checklist for provider sweeps.
   */
  expectedEventKinds: AgentStoredEventKind[];
  notes?: string;
};

const textTurnEvents = [
  "user_message",
  "assistant_message_chunk",
  "assistant_message_end",
  "status",
] as const satisfies readonly AgentStoredEventKind[];

const toolEvents = [
  "tool_call",
  "tool_call_update",
] as const satisfies readonly AgentStoredEventKind[];

const permissionEvents = [
  "permission_request",
  "permission_resolved",
] as const satisfies readonly AgentStoredEventKind[];

export const BACKEND_HARNESS_EXPECTATIONS: Record<
  AgentBackendId,
  BackendHarnessExpectation
> = {
  "cesium-agent": {
    expectedEventKinds: [
      ...textTurnEvents,
      "system_reminder",
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "question",
      "compression_summary",
      ...permissionEvents,
      "system",
      "agent_handoff",
      "chat_fork",
    ],
  },
  "cursor-sdk": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes: "Question and plan approval support must be verified against the installed SDK.",
  },
  "cursor-acp": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes: "Cursor Agent CLI over ACP (`agent acp`). OAuth/login works via the CLI; the TypeScript SDK does not expose that flow.",
  },
  "opencode-server": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "subagent",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Current dialect uses global/child SSE routing. The packaged v2 Beta dialect adds durable session logs, questions/forms, PTY/shell, and background subagents.",
  },
  "opencode-v2-beta": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "subagent",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Native v2 events use volatile live deltas plus cursor-resumable durable logs; background subagents have child log streams.",
  },
  "devin-acp": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      ...permissionEvents,
      "system",
    ],
    notes: "Devin CLI ACP (`devin acp`); richer CLI-only interactions may not surface over ACP.",
  },
  "grok-build": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "subagent",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Official Grok Build ACP (`grok agent stdio`); Cesium performs the advertised xai.api_key or cached_token authentication handshake before opening a session.",
  },
  "codex-app-server": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "subagent",
      ...permissionEvents,
      "system",
    ],
    notes: "plan_file is produced by the OpenCursor mirroring layer, not Codex itself.",
  },
  "codex-acp": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes: "Codex CLI over ACP (`codex acp`). Same ambient Codex login as the app server.",
  },
  "claude-code-sdk": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "subagent",
      "question",
      "compression_summary",
      "system_reminder",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Task list tools mirror into plan/plan_file; Agent tool calls render as subagent cards; AskUserQuestion bridges to question cards; compact_boundary maps to compression_summary.",
  },
  "pi-agent": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "question",
      ...permissionEvents,
      "system",
      "compression_summary",
    ],
  },
  "google-antigravity-cli": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      "plan_file",
      "subagent",
      "question",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Plan/todo events are mirrored from manage_task; MCP and prompt attachments are limited by Antigravity workspace config and CLI support.",
  },
  "google-antigravity-acp": {
    expectedEventKinds: [
      ...textTurnEvents,
      "reasoning",
      ...toolEvents,
      "plan",
      ...permissionEvents,
      "system",
    ],
    notes:
      "Google's official `agy_acp_server` over ACP stdio. Reasoning arrives as agent_thought_chunk, permissions as session/request_permission (mode `default`), plans via ACP plan updates; auth is Google OAuth handled inside the server.",
  },
};
