import type { ThemeTokensPartial } from "./theme-tokens";

export const DEFAULT_BUILTIN_THEME_ID = "default" as const;

export type BuiltinThemePreset = {
  label: string;
  light: ThemeTokensPartial;
  dark: ThemeTokensPartial;
};

/** Built-in catalog: each id defines optional light/dark partial overrides on defaults. */
export const BUILTIN_THEME_CATALOG: Record<string, BuiltinThemePreset> = {
  [DEFAULT_BUILTIN_THEME_ID]: {
    label: "Default",
    light: {},
    dark: {},
  },
  "high-contrast-light": {
    label: "High contrast (light)",
    light: {
      "--text-primary": "#000000",
      "--text-secondary": "#1a1a1a",
      "--border-card": "#000000",
      "--border-subtle": "#333333",
      "--bg-main": "#ffffff",
      "--bg-panel": "#f5f5f5",
      "--accent": "#000000",
    },
    dark: {},
  },
  "high-contrast-dark": {
    label: "High contrast (dark)",
    light: {},
    dark: {
      "--text-primary": "#ffffff",
      "--text-secondary": "#e0e0e0",
      "--border-card": "#cccccc",
      "--border-subtle": "#666666",
      "--bg-main": "#000000",
      "--bg-panel": "#0a0a0a",
      "--accent": "#ffffff",
    },
  },
  "warm-light": {
    label: "Warm paper",
    light: {
      "--bg-main": "#f7f4ef",
      "--bg-panel": "#efe9df",
      "--bg-card": "#e8e0d4",
      "--border-subtle": "#ddd5c8",
      "--plan-accent-bg": "#f0e8d8",
    },
    dark: {},
  },
  "forest-dark": {
    label: "Forest",
    light: {},
    dark: {
      "--bg-main": "#152018",
      "--bg-panel": "#1a2820",
      "--bg-card": "#24352a",
      "--border-subtle": "#2d4034",
      "--ask-accent": "#7cba8f",
      "--ask-accent-bg": "#1e3026",
    },
  },
  "oled": {
    label: "OLED black",
    light: {},
    dark: {
      "--background": "#000000",
      "--bg-main": "#000000",
      "--bg-panel": "#0a0a0a",
      "--bg-card": "#141414",
      "--bg-tab-active": "#000000",
      "--border-subtle": "#1a1a1a",
    },
  },
  "dusk": {
    label: "Dusk purple",
    light: {},
    dark: {
      "--bg-main": "#1a1625",
      "--bg-panel": "#221c32",
      "--bg-card": "#2e2640",
      "--border-card": "#4a3f63",
      "--border-subtle": "#332a47",
      "--accent-bg": "rgba(180, 160, 255, 0.12)",
    },
  },
  "frost-light": {
    label: "Frost (light)",
    light: {
      "--bg-main": "#f4f7fb",
      "--bg-panel": "#e8eef6",
      "--bg-card": "#dde5f0",
      "--border-subtle": "#c8d4e4",
      "--border-card": "#9eb4ce",
      "--text-primary": "#142333",
      "--text-secondary": "#3d5166",
      "--accent": "#1e5a8a",
      "--accent-dark": "#164a72",
      "--palette-row-selected-bg": "#cfe5f8",
      "--palette-keybinding-on-selected": "#0d4f82",
    },
    dark: {},
  },
  "sepia-light": {
    label: "Sepia reader",
    light: {
      "--background": "#f4ecd8",
      "--foreground": "#2c2416",
      "--bg-main": "#f4ecd8",
      "--bg-panel": "#ebe3cf",
      "--bg-card": "#e0d8c4",
      "--border-subtle": "#d4cbb5",
      "--text-primary": "#2c2416",
      "--text-secondary": "#5c5040",
      "--accent": "#6b4f2a",
      "--palette-surface": "#faf6ea",
    },
    dark: {},
  },
  "mint-light": {
    label: "Mint",
    light: {
      "--bg-main": "#f2faf6",
      "--bg-panel": "#e6f2eb",
      "--bg-card": "#d8ebe0",
      "--border-subtle": "#c5dccf",
      "--ask-accent": "#2d6b4a",
      "--ask-accent-bg": "#dceee4",
      "--plan-accent-bg": "#e8f0e4",
      "--text-primary": "#153525",
    },
    dark: {},
  },
  "blush-light": {
    label: "Blush",
    light: {
      "--bg-main": "#fcf6f8",
      "--bg-panel": "#f8eef2",
      "--bg-card": "#f0e4ea",
      "--border-subtle": "#e5d4dc",
      "--accent": "#8b3a62",
      "--accent-bg": "rgba(139, 58, 98, 0.1)",
      "--plan-accent": "#7a4a6a",
      "--plan-accent-bg": "#f2e6ee",
    },
    dark: {},
  },
  "slate-light": {
    label: "Slate",
    light: {
      "--bg-main": "#f1f3f5",
      "--bg-panel": "#e6e9ed",
      "--bg-card": "#dce1e7",
      "--text-primary": "#1c2128",
      "--border-subtle": "#cfd6de",
      "--palette-surface": "#ffffff",
      "--palette-border": "#aeb8c4",
    },
    dark: {},
  },
  "solar-light": {
    label: "Solar cream",
    light: {
      "--bg-main": "#fdf6e3",
      "--bg-panel": "#f5ecd4",
      "--bg-card": "#eee8c8",
      "--text-primary": "#3d3a2e",
      "--text-secondary": "#657177",
      "--border-subtle": "#e3d9c0",
      "--plan-accent": "#b58900",
      "--plan-accent-bg": "#f3ead0",
      "--debug-accent": "#cb4b16",
    },
    dark: {},
  },
  "arctic-light": {
    label: "Arctic",
    light: {
      "--bg-main": "#fafcfd",
      "--bg-panel": "#f0f4f8",
      "--bg-card": "#e5ecf4",
      "--accent": "#0c6b9e",
      "--palette-row-selected-bg": "#d3ebff",
      "--border-subtle": "#d9e5ee",
    },
    dark: {},
  },
  "lavender-light": {
    label: "Lavender",
    light: {
      "--bg-main": "#f7f5fc",
      "--bg-panel": "#eee9f8",
      "--bg-card": "#e4ddf3",
      "--border-subtle": "#d8cfec",
      "--accent": "#5c4d9d",
      "--accent-bg": "rgba(92, 77, 157, 0.1)",
      "--palette-row-selected-bg": "#e4dafb",
    },
    dark: {},
  },
  "nord-dark": {
    label: "Nord night",
    light: {},
    dark: {
      "--bg-main": "#2e3440",
      "--bg-panel": "#3b4252",
      "--bg-card": "#434c5e",
      "--border-subtle": "#3b4252",
      "--border-card": "#4c566a",
      "--text-primary": "#eceff4",
      "--text-secondary": "#d8dee9",
      "--accent": "#88c0d0",
      "--accent-dark": "#8fbcbb",
      "--palette-row-selected-bg": "#5e81ac",
      "--palette-row-selected-text": "#eceff4",
      "--ask-accent": "#a3be8c",
      "--ask-accent-bg": "#3b4252",
      "--plan-accent": "#ebcb8b",
      "--plan-accent-bg": "#434c5e",
    },
  },
  "dracula-dark": {
    label: "Dracula",
    light: {},
    dark: {
      "--bg-main": "#282a36",
      "--bg-panel": "#343746",
      "--bg-card": "#44475a",
      "--border-subtle": "#44475a",
      "--border-card": "#6272a4",
      "--text-primary": "#f8f8f2",
      "--accent": "#bd93f9",
      "--accent-dark": "#ff79c6",
      "--palette-row-selected-bg": "#44475a",
      "--palette-keybinding-on-selected": "#ff79c6",
      "--ask-accent": "#50fa7b",
      "--ask-accent-bg": "#343746",
      "--debug-accent": "#ff5555",
    },
  },
  "espresso-dark": {
    label: "Espresso",
    light: {},
    dark: {
      "--bg-main": "#1c1612",
      "--bg-panel": "#251f1a",
      "--bg-card": "#322a22",
      "--border-subtle": "#3d3329",
      "--text-primary": "#ebe3d9",
      "--text-secondary": "#a89888",
      "--accent": "#d4a574",
      "--plan-accent": "#c9a227",
      "--plan-accent-bg": "#3a3025",
    },
  },
  "midnight-dark": {
    label: "Midnight blue",
    light: {},
    dark: {
      "--bg-main": "#0d1421",
      "--bg-panel": "#121b2b",
      "--bg-card": "#1a2740",
      "--border-subtle": "#243352",
      "--accent": "#6eb5ff",
      "--palette-row-selected-bg": "#1e3a5f",
      "--palette-keybinding-on-selected": "#7ec8ff",
      "--text-primary": "#e8f0ff",
    },
  },
  "amber-dark": {
    label: "Amber terminal",
    light: {},
    dark: {
      "--bg-main": "#14110a",
      "--bg-panel": "#1c1810",
      "--bg-card": "#282015",
      "--text-primary": "#f8e7c8",
      "--text-secondary": "#c4a574",
      "--accent": "#ffb020",
      "--border-subtle": "#3d331f",
      "--palette-row-selected-bg": "#3d3018",
      "--palette-icon-json": "#ffb020",
    },
  },
  "teal-dark": {
    label: "Deep teal",
    light: {},
    dark: {
      "--bg-main": "#0c1818",
      "--bg-panel": "#102222",
      "--bg-card": "#163030",
      "--border-subtle": "#1f4240",
      "--accent": "#5ee4d3",
      "--ask-accent": "#4dd4b8",
      "--ask-accent-bg": "#143028",
      "--palette-row-selected-bg": "#14524a",
    },
  },
  "ruby-dark": {
    label: "Ruby wine",
    light: {},
    dark: {
      "--bg-main": "#1a1014",
      "--bg-panel": "#24161c",
      "--bg-card": "#321f28",
      "--border-subtle": "#422a35",
      "--accent": "#f0719a",
      "--debug-accent": "#ff8a9b",
      "--text-primary": "#fdeef2",
    },
  },
  "charcoal-dark": {
    label: "Charcoal",
    light: {},
    dark: {
      "--bg-main": "#121212",
      "--bg-panel": "#1a1a1a",
      "--bg-card": "#242424",
      "--border-subtle": "#2c2c2c",
      "--text-primary": "#e4e4e4",
      "--text-secondary": "#9a9a9a",
      "--palette-surface": "#1e1e1e",
    },
  },
  "rose-gold-dark": {
    label: "Rose gold",
    light: {},
    dark: {
      "--bg-main": "#1b1416",
      "--bg-panel": "#261c1f",
      "--bg-card": "#34262b",
      "--border-subtle": "#403036",
      "--accent": "#e8b5a0",
      "--plan-accent": "#d4a574",
      "--plan-accent-bg": "#3a2c28",
      "--text-primary": "#faf0eb",
    },
  },
  "cyber-dark": {
    label: "Cyber ice",
    light: {},
    dark: {
      "--bg-main": "#0a0f14",
      "--bg-panel": "#0f1620",
      "--bg-card": "#15202d",
      "--border-subtle": "#1e2d3d",
      "--accent": "#00e5ff",
      "--accent-dark": "#00b4d8",
      "--text-primary": "#e8f8ff",
      "--palette-row-selected-bg": "#0c3d52",
      "--palette-keybinding-on-selected": "#48e0ff",
    },
  },
  "mono-light": {
    label: "Mono paper",
    light: {
      "--bg-main": "#ffffff",
      "--bg-panel": "#f2f2f2",
      "--bg-card": "#e8e8e8",
      "--text-primary": "#111111",
      "--text-secondary": "#555555",
      "--border-card": "#cccccc",
      "--border-subtle": "#e0e0e0",
      "--accent": "#222222",
    },
    dark: {},
  },
  "mono-dark": {
    label: "Mono ink",
    light: {},
    dark: {
      "--bg-main": "#111111",
      "--bg-panel": "#181818",
      "--bg-card": "#222222",
      "--text-primary": "#f2f2f2",
      "--text-secondary": "#a0a0a0",
      "--border-subtle": "#2a2a2a",
      "--border-card": "#3a3a3a",
      "--accent": "#e8e8e8",
    },
  },
  "sakura-light": {
    label: "Sakura",
    light: {
      "--bg-main": "#fff8fa",
      "--bg-panel": "#ffeff4",
      "--bg-card": "#ffe6ee",
      "--border-subtle": "#f5d0dc",
      "--text-primary": "#4a2c36",
      "--accent": "#c94f7c",
      "--plan-accent-bg": "#fce8ef",
    },
    dark: {},
  },
  "graphite-dark": {
    label: "Graphite",
    light: {},
    dark: {
      "--bg-main": "#161618",
      "--bg-panel": "#1c1c1f",
      "--bg-card": "#252528",
      "--border-subtle": "#2e2e32",
      "--text-primary": "#f2f2f7",
      "--accent": "#a1a1a6",
      "--palette-surface": "#1e1e21",
    },
  },
  "sand-light": {
    label: "Sand dune",
    light: {
      "--bg-main": "#f9f4ec",
      "--bg-panel": "#efe6d8",
      "--bg-card": "#e5dac9",
      "--border-subtle": "#d9cbb8",
      "--text-primary": "#3a3228",
      "--plan-accent": "#8b6914",
      "--plan-accent-bg": "#efe3c8",
    },
    dark: {},
  },
  "horizon-dark": {
    label: "Horizon sunset",
    light: {},
    dark: {
      "--bg-main": "#1f1418",
      "--bg-panel": "#2a1820",
      "--bg-card": "#3a2430",
      "--border-subtle": "#4a3040",
      "--accent": "#ff8c69",
      "--text-primary": "#fff2ed",
      "--plan-accent": "#e07850",
      "--plan-accent-bg": "#3a2825",
    },
  },
};

export function listBuiltinThemeIds(): string[] {
  return Object.keys(BUILTIN_THEME_CATALOG);
}

export function isBuiltinThemeId(id: string): boolean {
  return id in BUILTIN_THEME_CATALOG;
}
