// Moved to @cesium/client (packages/client/src/agent-shell-layout.ts). Re-export shim keeps existing imports stable.
export {
  AGENT_CENTER_CONTENT_CLASS,
  AGENT_CENTER_STAGE_CLASS,
  AGENT_LEFT_RAIL_COLLAPSED_SIZE_PERCENT,
  AGENT_LEFT_RAIL_COLLAPSED_WIDTH,
  AGENT_LEFT_RAIL_EXPANDED_WIDTH,
  AGENT_RIGHT_PANE_WIDTH,
  AGENT_SHELL_CENTER_MIN_PERCENT,
  AGENT_SHELL_DEFAULT_LAYOUT,
  AGENT_SHELL_PANEL_IDS,
  AGENT_SHELL_RAIL_MAX_PERCENT,
  AGENT_SHELL_RAIL_MIN_PERCENT,
  AGENT_SHELL_SIDE_MAX_PERCENT,
  AGENT_SHELL_SIDE_MIN_PERCENT,
  collapseAgentShellSideLayout,
  composeAgentShellDesktopLayout,
  extractAgentSidePaneScopedLayout,
  getAgentShellRailPixelWidth,
  isAgentSidePaneScopedLayout,
  normalizeAgentShellDesktopLayout,
  readAgentShellSharedSnapshot,
  writeAgentShellSharedSnapshot,
} from "@cesium/client";
